export interface Measurement {
  id: string,
  patientId: string,
  measurementDate: string,
  displayDate: string,
  bodyWeight: number,
  breast: number,
  underBreast: number,
  waist: number,
  abdominal: number,
  hipBones: number,
  hips: number,
  thighWidest: number,
  thighNarrowest: number,
  calf: number,
  chest: number,
  arm: number,
}
