export var ALLERGEN_TYPES = [
  { id: "GLUTEN", value: "Gluten" },
  { id: "LACTOSE", value: "Laktoza" },
  { id: "STARCH", value: "Skrobia" },
  { id: "EGGS", value: "Jaja" },
  { id: "FISH", value: "Ryby" },
  { id: "NUTS", value: "Orzechy" },
  { id: "PEANUTS", value: "Orzechy arachidowe" },
  { id: "SOY", value: "Soja" },
  { id: "CELERY", value: "Seler" },
  { id: "MUSTARD", value: "Gorczyca" },
  { id: "SESAM", value: "Sezam" },
  { id: "SULPHUR_DIOXIDE", value: "Dwutl. siarki" },
  { id: "LUPINE", value: "Łubin" },
  { id: "MOLLUSCS", value: "Mięczaki" },
];
